export default {
  LOGIN_STATUS: 'LOGIN_STATUS',
  LOADING_STATUS: 'LOADING_STATUS',
  UPDATE_MESSAGES: 'UPDATE_MESSAGES',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_DASHBOARD: 'UPDATE_DASHBOARD'
};
